project:
  type: website
  output-dir: docs

website:
  title: "temp_website"
  favicon: favicon.png
  navbar:
    logo: logo.png
    left:
      - href: index.qmd
        text: "Home"
      - href: fyp.qmd       
        text: "Final Year Project"
      - href: learning.qmd
        text: "Learning"   
      - href: travel.qmd   
        text: "travel"
      - href: reflection.qmd   
        text: "reflection"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left

css: styles.css

  
editor: visual

